Repository nacos-group/nacos-sdk-rust, pull requests merged in 2022-11, with the labels that each got.

#52 Change: server-addr 默认 0.0.0.0:8848，grpc 链接端口+1000
  README.md
  examples/simple_app.rs
  src/api/config.rs
  src/api/constants.rs
  src/api/props.rs
  src/common/remote/grpc/grpc_client.rs
  src/common/remote/grpc/mod.rs
  src/common/remote/mod.rs
  src/lib.rs
  src/naming/mod.rs
Labels: core

#54 Doc: add doc and upgrade 0.2.0
  Cargo.toml
  README.md
  examples/simple_app.rs
  src/api/events/mod.rs
  src/api/mod.rs
  src/common/executor/mod.rs
  src/common/remote/grpc/message/response/mod.rs
  src/lib.rs
Labels: documentation, chore

#58 [ISSUE #18] Feature: Auth 鉴权；账密登陆 accessToken
  Cargo.toml
  nacos-macro/src/request.rs
  src/api/config.rs
  src/api/naming.rs
  src/api/plugin/auth/auth_by_http.rs
  src/api/plugin/auth/mod.rs
  src/api/plugin/mod.rs
  src/api/props.rs
  src/common/remote/grpc/message/mod.rs
  src/config/mod.rs
  src/config/worker.rs
  src/naming/mod.rs
Labels: enhancement, core

#57 upgrade: grpcio=0.12, prost=0.11
  Cargo.toml
  src/_.rs
  tests/proto_build.rs
Labels: core, chore

#65 optimized code, optimized dependencies
  Cargo.toml
  README.md
  src/api/plugin/auth/auth_by_http.rs
Labels: chore

#68 [ISSUES #67] naming service push
  src/api/events/naming/instances_change_event.rs
  src/common/remote/grpc/message/mod.rs
  src/naming/dto/mod.rs
  src/naming/handler/naming_push_request_handler.rs
  src/naming/mod.rs
Labels: enhancement, naming

#72 doc: chore doc naming.
  README.md
  examples/simple_app.rs
  src/api/naming.rs
  src/naming/mod.rs
Labels: documentation, chore
