Repository nacos-group/nacos-sdk-rust, pull requests merged in 2023-02, with the labels that each got.

#95 chore: Optimize and Unified code.
  src/api/constants.rs
  src/api/error.rs
  src/common/executor/mod.rs
  src/config/handler.rs
  src/config/worker.rs
  src/naming/mod.rs
Labels: chore

#98 ci: fix codecov tarpaulin with 0.22.0
  .github/workflows/codecov.yml
Labels: chore

#105 doc: link to nacos-sdk-rust-binding-node
  README.md
Labels: documentation, chore

#108 [ISSUES #107] Add asynchronous api
  Cargo.toml
  src/api/config.rs
  src/api/naming.rs
  src/config/mod.rs
  src/config/worker.rs
  src/naming/mod.rs
Labels: enhancement

#110 chore: upgrade version to 0.2.3
  CHANGELOG.md
  Cargo.toml
  README.md
  src/api/config.rs
  src/api/naming.rs
  src/config/mod.rs
  src/lib.rs
  src/naming/mod.rs
Labels: documentation, chore
