Repository nacos-group/nacos-sdk-rust, pull requests merged in 2023-04, with the labels that each got.

#135 opt: env `NACOS_CLIENT_COMMON_THREAD_CORES` to set worker_threads
  src/api/constants.rs
  src/common/executor/mod.rs
  src/config/worker.rs
Labels: chore

#136 opt: log instrument & into_grpc_server_addr
  src/common/remote/grpc/grpc_client.rs
  src/common/remote/grpc/mod.rs
  src/config/mod.rs
  src/config/worker.rs
  src/naming/mod.rs
  src/naming/updater/mod.rs
Labels: chore

#137 opt: log instrument conn_id
  src/common/remote/grpc/message/mod.rs
  src/common/remote/grpc/mod.rs
  src/common/remote/grpc/subscribers/connection_health_check_subscriber.rs
  src/common/remote/grpc/subscribers/reconnected_subscriber.rs
  src/config/worker.rs
  src/naming/handler/naming_push_request_handler.rs
  src/naming/subscribers/instances_change_event_subscriber.rs
  src/naming/subscribers/redo_task_disconnect_event_subscriber.rs
  src/naming/subscribers/redo_task_reconnect_event_subscriber.rs
  src/naming/updater/mod.rs
Labels: chore

#138 refactor grpc client, use tonic instead of grpc-rs
  Cargo.toml
  build.rs
  src/_.rs
  src/api/error.rs
  src/common/executor/mod.rs
  src/common/remote/grpc/bi_channel.rs
  src/common/remote/grpc/config.rs
  src/common/remote/grpc/events/client_init_complete_event.rs
  src/common/remote/grpc/events/connection_health_check_event.rs
  src/common/remote/grpc/events/disconnect_event.rs
  src/common/remote/grpc/events/mod.rs
  src/common/remote/grpc/events/reconnected_event.rs
  src/common/remote/grpc/events/shutdown_event.rs
  src/common/remote/grpc/grpc_client.rs
  src/common/remote/grpc/handler/client_detection_request_handler.rs
  src/common/remote/grpc/handler/default_handler.rs
  src/common/remote/grpc/handler/mod.rs
  src/common/remote/grpc/handlers/client_detection_request_handler.rs
  src/common/remote/grpc/handlers/default_handler.rs
  src/common/remote/grpc/handlers/mod.rs
  src/common/remote/grpc/message/request/set_up_request.rs
  src/common/remote/grpc/mod.rs
  src/common/remote/grpc/nacos_grpc_client.rs
  src/common/remote/grpc/nacos_grpc_connection.rs
  src/common/remote/grpc/nacos_grpc_service.rs
  src/common/remote/grpc/server_list_service.rs
  src/common/remote/grpc/subscribers/connection_health_check_subscriber.rs
  src/common/remote/grpc/subscribers/mod.rs
  src/common/remote/grpc/subscribers/reconnected_subscriber.rs
  src/common/remote/grpc/tonic.rs
  src/config/handler.rs
  src/config/worker.rs
  src/lib.rs
  src/naming/handler/naming_push_request_handler.rs
  src/naming/mod.rs
  src/naming/redo/automatic_request/batch_instance_request.rs
  src/naming/redo/automatic_request/instance_request.rs
  src/naming/redo/automatic_request/subscribe_service_request.rs
  src/naming/redo/mod.rs
  src/naming/subscribers/mod.rs
  src/naming/subscribers/redo_task_disconnect_event_subscriber.rs
  src/naming/subscribers/redo_task_reconnect_event_subscriber.rs
  src/naming/updater/mod.rs
  tests/proto_build.rs
Labels: enhancement, core

#144 chore: `#![deny(rust_2018_idioms, clippy::disallowed_methods, clippy::disallowed_types)]`
  .clippy.toml
  src/api/plugin/auth/auth_by_http.rs
  src/lib.rs
Labels: chore

#148 enhance: adjust server list service parse pattern
  src/common/remote/grpc/config.rs
  src/common/remote/grpc/nacos_grpc_client.rs
  src/common/remote/grpc/server_list_service.rs
  src/common/remote/grpc/tonic.rs
Labels: core
